version: '3.8'

services:
  api:
    container_name: money-tracker-api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.pnpm-store
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env.${NODE_ENV:-development}
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-money_tracker}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - money-tracker-network

  postgres:
    container_name: money-tracker-db
    image: postgres:15-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-money_tracker}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - money-tracker-network

volumes:
  postgres-data:

networks:
  money-tracker-network:
    driver: bridge
